apiVersion: v1
kind: Namespace
metadata:
  name: eshop
  labels:
    app.kubernetes.io/name: eshop
    app.kubernetes.io/instance: eshop
---
apiVersion: v1
kind: Secret
metadata:
  namespace: eshop
  name: paypal-rest-api
type: Opaque
data:
  PAYPAL_CLIENT_ID: {PAYPAL_CLIENT_ID}
  PAYPAL_SECRET: {PAYPAL_SECRET}



